config/routes.rb
Tithe::Application.routes.draw do

  root :to => 'pages#home'

  get 'login' => 'sessions#new', :as => 'login'
  get 'logout' => 'sessions#destroy', :as => 'logout'
  get 'sign_up' => 'users#new', :as => 'sign_up'
  resources :transactions
  resources :organizations
  resources :users
  resources :sessions, :only => [ :create ]

end

app/models/organization.rb
class Organization < ActiveRecord::Base
  attr_accessible :description, :name
  belongs_to :user
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  attr_accessible :amount, :organization_id, :user_id, :stripe_card_token
  attr_accessor :stripe_card_token

  belongs_to :user
  belongs_to :organization

  def save_with_payment
    if valid?
      customer = Stripe::Customer.create(:description => self.user.email, :card => stripe_card_token)
      self.stripe_customer_token = customer.id
      save!
    end
  rescue Stripe::InvalidRequestError => e
    logger.error "Stripe error while creating customer: #{e.message}"
    errors.add :base, "There was a problem with your credit card."
    false
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  attr_accessible :email, :first_name, :last_name, :password, :password_confirmation
  has_many :transactions
  has_many :organizations
  validates :email, :uniqueness => true

  def self.authenticate(email, password)
    find_by_email(email).try(:authenticate, password)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_user=(user)
    session.clear
    session[:user_id] = user.id
  end

  def authenticate_user!
    redirect_to login_path unless current_user
  end

  def check_current_user
    redirect_to organizations_path if current_user
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController

  def new
    @organization = Organization.new
  end

  def create
    @organization = Organization.new(params[:organization])
    if @organization.save
      redirect_to @organization, :notice => "Organization saved successfully."
    else
      render :new
    end
  end

  def show
    @organization = Organization.find(params[:id])
  end

  def edit
    @organization = Organization.find(params[:id])
  end

  def update
    @organization = Organization.find(params[:id])
    if @organization.update_attributes(params[:organization])
     redirect_to @organization, :notice => 'Organization was successfully updated.'
    end
  end

  def destroy
     @organization = Organization.find(params[:id])
     @organization.destroy
     redirect_to organizations_path, :notice => 'Organization was successfully deleted.'
  end

  def index
    @organizations = Organization.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_filter :check_current_user, :only => [ :new, :create ]

  def new
  end

  def create
    if user = User.authenticate(params[:email], params[:password])
      self.current_user = user
      redirect_to organizations_path, :notice => "Logged in!"
    else
      flash.now[:error] = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session.clear
    redirect_to root_path, :notice => "Logged out!"
  end

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def new
    @transaction = Transaction.new
  end

  def create
    @transaction = Transaction.new(params[:transaction])
    if @transaction.save_with_payment
      redirect_to root_path
      # @transaction, :notice => "Thank you for contributing!"
    else
      render :new
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :check_current_user

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      Notifier.welcome(@user).deliver
      self.current_user = @user
      redirect_to organizations_path, :notice => "Signed up!"
    else
      flash.now[:error] = 'There was a problem creating your account'
      render "new"
    end
  end
end

app/views/layouts/_carousel.html.haml
#myCarousel{ :class => "carousel slide" }
  .carousel-inner
    %div{ :class => "active item" }= image_tag("slide_a.jpg")
    .item= image_tag("slide_b.jpg")
    .item= image_tag("slide_c.jpg")
    .item= image_tag("slide_d.jpg")
  = link_to("‹", "#myCarousel", :class => "carousel-control left", "data-slide" => "prev")
  = link_to("›", "#myCarousel", :class => "carousel-control right", "data-slide" => "next")

app/views/layouts/_footer.html.haml
%footer
  .container
    .row
      .span3
        #jstwitter
          %h3 Twitter Feed
      .span3
        %h3 Latest News
        %p
          Tithe launches at SF Startup Weekend.
          = link_to "Read More", "http://swbay.startupweekend.org/"
        %p
          Anonymous donor makes $1M contribution to Big Bend National Park.
          %a{:href => "#"}Read More
      .span3
        %h3 Contact Us!
        Have a question or comment? We can help you!
        %br
        %br
        by phone: (415)-453-5555
        %br
        by mail: titheswsf@gmail.com
      .span3
        %h3 Newsletter
        %p Subscribe to our newsletter and get the latest updates!
        %form{:action => "#", :id => "subscribe-form", :method => "post"}
          %input{:type => "text", :name => "email", :id => "email", :placeholder => "Your Email Address"}
          %button{:type => "submit", :class => "btn btn-primary"} Sign Up
    %p &copy; Tithe 2012

app/views/layouts/_header.html.erb
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <div>
            <%= link_to "tithe.org", root_path, :class => "brand" %>
          </div>
          <div class="container nav-collapse">
            <ul class="nav pull-right">

              <li><% if current_user %><%= link_to "Log Out", logout_path  %><% end %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

app/views/layouts/_shim.html.erb
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Tithe" %></title>
    <%= csrf_meta_tags %>
    <%= tag :meta, :name => "stripe-key", :content => ENV['STRIPE_PUBLIC_TEST_KEY'] %>
    <%= render 'layouts/shim' %>
    <%= stylesheet_link_tag "application", :media => "all" %>
  </head>
  <body>

    <%= render 'layouts/header' %>

    <div class="container">
      <div class="content">
            <% flash.each do |key,value| %>
          <%= content_tag(:div, value, :class => "alert alert-#{key}") %>
        <% end %>
        <div class="row">
           <div class="span12">
              <%= yield %>
            </div>
        </div><!--/row-->
      </div><!--/content-->
  </br></br>

    <%= render 'layouts/footer' %>
    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
  <%= javascript_include_tag "https://js.stripe.com/v1/", "application" %>

  </body>
</html>

app/views/notifier/welcome.html.haml
%h3 Hi, #{@user.first_name}!

%p
  Thanks so much for joining Tithe!  Let's get started contributing:

%h3= link_to("Tithe", "http://tithe.boon.gl")

%p
  Cheers!
  %br
  The Tithe team

app/views/organizations/_form.html.erb
<%= form_for(@organization) do |f|%>
  <div class="field">
    <%= f.label "Organization name:" %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label "Organization description:" %>
    <%= f.text_area :description, :rows => 5 %>
  </div>

  <div class="actions">
    <%= f.submit "Submit Organization", :class=>"btn btn-primary btn-large" %>
  </div>
<% end %>

app/views/organizations/edit.html.erb
<%= render 'form' %>

app/views/organizations/index.html.erb
<h1>All Organizations</h1>
<h3><div class="center"><%= link_to 'Add New Organization', new_organization_path, :class => "btn btn-primary btn-large" %>  <%= link_to 'Contribute to an organization', new_transaction_path, :class => "btn btn-primary btn-large" %></div></h3>
<table>
  <tr>
    <th>Organization Name</th>
    <th>Organization Description</th>
  </tr>

  <% @organizations.each do |org| %>
    <tr>
      <td><%= org.name %></td>
      <td><%= org.description %> </td>
    </tr>
  <% end %>
</table>

app/views/organizations/new.html.erb
<%= render 'form' %>

app/views/organizations/show.html.erb
<h1><%= @organization.name %> </h1>
<p> <%= @organization.description %> </p>
<%= link_to "View all organizations", organizations_path %>

app/views/pages/_steps.html.erb
  <div class="row">
    <div class="span1">
          <%= image_tag("icon.png") %>
        </div>
        <div class="span3">
          <h3>Step 1</h3>
          <p>Find the organizations and agencies that you want to support.  Our extensive database offers unique insights into each organization's services.</p>
        </div>
       <div class="span1">
          <%= image_tag("icon.png") %>
       </div>
       <div class="span3">
          <h3>Step 2</h3>
          <p>Tithe's easy-to-use interface allows you to make a one-time contribution or a monthly payment.  Cancel at anytime.</p>
        </div>

        <div class="span1">
          <%= image_tag("icon.png") %>
        </div>
        <div class="span3">
          <h3>Step 3</h3>
          <p>Receive regular updates on how your supported organizations are doing.  Meet and communicate with others who share similar interests.</p>
        </div>
    </div>
  <p></p>

app/views/pages/home.html.erb
<%= render 'layouts/carousel' %>
<h2>Welcome to Tithe.</h2>
<h3>We help citizens support the governmental agencies they care most about. </h3>
<p>The government--whether federal, state, or local--provides many vital services that we depend on.  These services include everything from the streets we drive on, the schools our children are educated in, and the public transportation that help us get to work. </p>
<p> Public spending has been drastically reduced in many key areas over the last few years due to the economic recession.  These reductions have meant <strong>fewer afterschool programs</strong>, <strong>fewer operating hours for local libraries</strong>, <strong>fewer police officers keeping our neighborhoods safe</strong>, and <strong>fewer services in every manner</strong>.</p>
<p> Tithe exists to connect citizens with the governmental agencies you support most.  Through Tithe, you can easily make a donation to help support the government service of your choice. </p>
<div class="center"><%= link_to "Join today!", sign_up_path, :class => "btn btn-primary btn-large", :method => :get %> <%= link_to "Log in!", login_path, :class => "btn btn-primary btn-large", :method => :get %></div>
<br><br><br><br>
<%= render 'pages/steps' %>

app/views/transactions/new.html.erb
<h1>Make a contribution</h1>

<%= form_for @transaction do |f| %>
  <% if @transaction.errors.any? %>
    <div class="error_messages">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>
      <ul>
      <% @transaction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :organization_id %>
  <%= f.hidden_field :user_id %>
  <%= f.hidden_field :stripe_card_token %>

  <div class="field">
    <%= f.label :amount, "Monthly Contribution.  You may cancel at anytime" %>
    <%= f.text_field :amount, :placeholder => "$" %>
  </div>
  <% if @transaction.stripe_card_token.present? %>
    Credit card information has already been provided.
  <% else %>
    <div class="field">
      <%= label_tag :card_number, "Credit Card Number" %>
      <%= text_field_tag :card_number, nil, :name => nil %>
    </div>
    <div class="field">
      <%= label_tag :card_code, "Security Code on Card (CVV)" %>
      <%= text_field_tag :card_code, nil, :name => nil %>
    </div>
    <div class="field">
      <%= label_tag :card_month, "Card Expiration" %>
      <%= select_month nil, {:add_month_numbers => true}, {:name => nil, :id => "card_month"} %>
      <%= select_year nil, {:start_year => Date.today.year, :end_year => Date.today.year+5}, {:name => nil, :id => "card_year"} %>
    </div>
  <% end %>
  <div id="stripe_error">
    <noscript>JavaScript is not enabled and is required for this form. Please enable it in your web browser settings.</noscript>
  </div>
  <div class="actions">
    <%= f.submit "Contribute!", :class => "btn btn-primary" %>
  </div>
<% end %>

<%=debug @transaction %>

app/views/users/new.html.haml
<h1>Sign Up</h1>

= form_for @user do |f|
  - if @user.errors.any?
    .error_messages
      %h2 Form is invalid
      %ul
        - @user.errors.full_messages.each do |message|
          %li= message
  %p
    = f.label :first_name
    = f.text_field :first_name
  %p
    = f.label :last_name
    = f.text_field :last_name
  %p
    = f.label :email
    = f.text_field :email
  %p
    = f.label :password
    = f.password_field :password
  %p
    = f.label :password_confirmation
    = f.password_field :password_confirmation
  %p= submit_tag('Sign In', :class=> "btn btn-primary")